### ISSUE TITLE
[BUG] ASUS Zenbook S 14: No sound from DMIC

### ISSUE THREAD

**Issue by dantmnf** [thesofproject/linux#5325]
**Describe the bug**
Recording from DMIC generates a few pulses then a flat signal.

**To Reproduce**
```console
% arecord -l
**** List of CAPTURE Hardware Devices ****
card 0: sofsoundwire [sof-soundwire], device 1: Jack In (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: sofsoundwire [sof-soundwire], device 4: Microphone (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
% arecord -D hw:0,4 -f s16_le -r 48000 -c 2 -t wav -d 5 record.wav
Recording WAVE 'record.wav' : Signed 16 bit Little Endian, Rate 48000 Hz, Stereo
```

**Reproduction Rate**
All the time

**Expected behavior**
Should be able to record some sound

**Impact**
Unusable built-in microphone

**Environment**
1) Branch name and commit hash of the 2 repositories: sof (firmware/topology) and linux (kernel driver).
    * Kernel: stable 6.12.6
    * SOF: release v2024.09.2
2) Name of the topology file
    * Topology: intel/sof-ipc4-tplg/sof-lnl-cs42l43-l0-cs35l56-l23.tplg
3) Name of the platform(s) on which the bug is observed.
    * Platform: Lunar Lake

**Screenshots or console output**
![image](https://github.com/user-attachments/assets/78f4c78a-33d7-46ad-94d0-35795e510459)

alsa-info output for reference: 
[alsa-info.txt](https://github.com/user-attachments/files/18252368/alsa-info.txt)

P.S. recording from audio jack works.

**Comment by iradraconis** [comment]
Same here.. Using Linux Kernel 13.0 RC5 on Fedora and still the microphone is not functioning. 

Inxi output for Audio:

```
Audio:
  Device-1: Intel Lunar Lake-M HD Audio driver: sof-audio-pci-intel-lnl
  API: ALSA v: k6.13.0-0.rc5.42.fc42.x86_64 status: kernel-api
  Server-1: PipeWire v: 1.2.7 status: active
```
